In [13]:
import pandas as pd
df1=pd.read_csv("^spx_d (2).csv",index_col="Date")
df1.index=pd.to_datetime(df1.index,errors="coerce")
df2=pd.read_csv("^ndq_d (2).csv",index_col="Date")
df2.index=pd.to_datetime(df2.index,errors="coerce")
display(df1.describe())
display(df2.describe())

               Open          High           Low         Close        Volume
count  39649.000000  39649.000000  39649.000000  39649.000000  3.964900e+04
mean     454.409461    457.018550    451.627738    454.501635  3.392412e+08
std     1039.937914   1045.464246   1033.947492   1040.118815  7.981516e+08
min        0.490000      0.490000      0.490000      0.490000  0.000000e+00
25%        8.890000      8.900000      8.880000      8.890000  0.000000e+00
50%       18.790000     18.850000     18.720000     18.790000  0.000000e+00
75%      244.630000    246.380000    242.570000    244.670000  7.400000e+07
max     7002.000000   7002.280000   6963.460000   6978.600000  6.888367e+09

               Open          High           Low         Close        Volume
count  22772.000000  22772.000000  22772.000000  22772.000000  2.277200e+04
mean    1953.809535   1967.033346   1938.868838   1953.841294  7.441063e+08
std     3982.197045   4008.762132   3952.012317   3982.384501  1.264693e+09
min        4.610000      4.700000      4.450000      4.520000  0.000000e+00
25%       28.340000     28.340000     28.340000     28.340000  0.000000e+00
50%      178.500000    178.500000    178.500000    178.500000  0.000000e+00
75%     2055.350000   2069.115000   2039.635000   2055.575000  1.500599e+09
max    23987.290000  24019.990000  23775.490000  23958.470000  1.010879e+10

并排展示两个discribe输出

In [14]:
desc1=df1.describe()
desc2=df2.describe()
desc1.columns=[col+'_spx'for col in desc1.columns]
desc2.columns=[col+'_ndq'for col in desc2.columns]
combined=pd.concat([desc1,desc2],axis=1)
print(combined)

           Open_spx      High_spx       Low_spx     Close_spx    Volume_spx  \
count  39649.000000  39649.000000  39649.000000  39649.000000  3.964900e+04
mean     454.409461    457.018550    451.627738    454.501635  3.392412e+08
std     1039.937914   1045.464246   1033.947492   1040.118815  7.981516e+08
min        0.490000      0.490000      0.490000      0.490000  0.000000e+00
25%        8.890000      8.900000      8.880000      8.890000  0.000000e+00
50%       18.790000     18.850000     18.720000     18.790000  0.000000e+00
75%      244.630000    246.380000    242.570000    244.670000  7.400000e+07
max     7002.000000   7002.280000   6963.460000   6978.600000  6.888367e+09

           Open_ndq      High_ndq       Low_ndq     Close_ndq    Volume_ndq
count  22772.000000  22772.000000  22772.000000  22772.000000  2.277200e+04
mean    1953.809535   1967.033346   1938.868838   1953.841294  7.441063e+08
std     3982.197045   4008.762132   3952.012317   3982.384501  1.264693e+09
min        4.610000      4.700000      4.450000      4.520000  0.000000e+00
25%       28.340000     28.340000     28.340000     28.340000  0.000000e+00
50%      178.500000    178.500000    178.500000    178.500000  0.000000e+00
75%     2055.350000   2069.115000   2039.635000   2055.575000  1.500599e+09
max    23987.290000  24019.990000  23775.490000  23958.470000  1.010879e+10

横向拼接

In [15]:
desc1.index=[idx+'_spx'for idx in desc1.index]
desc2.index=[idx+'_ndq'for idx in desc2.index]
combined=pd.concat([desc1,desc2],axis=0)
print(combined)

               Open_spx      High_spx       Low_spx     Close_spx  \
count_spx  39649.000000  39649.000000  39649.000000  39649.000000
mean_spx     454.409461    457.018550    451.627738    454.501635
std_spx     1039.937914   1045.464246   1033.947492   1040.118815
min_spx        0.490000      0.490000      0.490000      0.490000
25%_spx        8.890000      8.900000      8.880000      8.890000
50%_spx       18.790000     18.850000     18.720000     18.790000
75%_spx      244.630000    246.380000    242.570000    244.670000
max_spx     7002.000000   7002.280000   6963.460000   6978.600000
count_ndq           NaN           NaN           NaN           NaN
mean_ndq            NaN           NaN           NaN           NaN
std_ndq             NaN           NaN           NaN           NaN
min_ndq             NaN           NaN           NaN           NaN
25%_ndq             NaN           NaN           NaN           NaN
50%_ndq             NaN           NaN           NaN           NaN
75%_ndq             NaN           NaN           NaN           NaN
max_ndq             NaN           NaN           NaN           NaN

             Volume_spx      Open_ndq      High_ndq       Low_ndq  \
count_spx  3.964900e+04           NaN           NaN           NaN
mean_spx   3.392412e+08           NaN           NaN           NaN
std_spx    7.981516e+08           NaN           NaN           NaN
min_spx    0.000000e+00           NaN           NaN           NaN
25%_spx    0.000000e+00           NaN           NaN           NaN
50%_spx    0.000000e+00           NaN           NaN           NaN
75%_spx    7.400000e+07           NaN           NaN           NaN
max_spx    6.888367e+09           NaN           NaN           NaN
count_ndq           NaN  22772.000000  22772.000000  22772.000000
mean_ndq            NaN   1953.809535   1967.033346   1938.868838
std_ndq             NaN   3982.197045   4008.762132   3952.012317
min_ndq             NaN      4.610000      4.700000      4.450000
25%_ndq             NaN     28.340000     28.340000     28.340000
50%_ndq             NaN    178.500000    178.500000    178.500000
75%_ndq             NaN   2055.350000   2069.115000   2039.635000
max_ndq             NaN  23987.290000  24019.990000  23775.490000

              Close_ndq    Volume_ndq
count_spx           NaN           NaN
mean_spx            NaN           NaN
std_spx             NaN           NaN
min_spx             NaN           NaN
25%_spx             NaN           NaN
50%_spx             NaN           NaN
75%_spx             NaN           NaN
max_spx             NaN           NaN
count_ndq  22772.000000  2.277200e+04
mean_ndq    1953.841294  7.441063e+08
std_ndq     3982.384501  1.264693e+09
min_ndq        4.520000  0.000000e+00
25%_ndq       28.340000  0.000000e+00
50%_ndq      178.500000  0.000000e+00
75%_ndq     2055.575000  1.500599e+09
max_ndq    23958.470000  1.010879e+10

In [16]:
display(df1.info())
display(df2.info())

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 39649 entries, 1789-05-01 to NaT
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    39649 non-null  float64
 1   High    39649 non-null  float64
 2   Low     39649 non-null  float64
 3   Close   39649 non-null  float64
 4   Volume  39649 non-null  int64
dtypes: float64(4), int64(1)
memory usage: 1.8 MB

None

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 22772 entries, 1938-01-03 to 2026-03-06
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    22772 non-null  float64
 1   High    22772 non-null  float64
 2   Low     22772 non-null  float64
 3   Close   22772 non-null  float64
 4   Volume  22772 non-null  int64
dtypes: float64(4), int64(1)
memory usage: 1.0 MB

None

In [17]:
common_start=max(df1.index.min(),df2.index.min())
common_end=min(df1.index.max(),df2.index.max())
print(f"共同时间区间:{common_start}至{common_end}")

共同时间区间:1938-01-03 00:00:00至1899-12-30 00:00:00

In [18]:
df1_common=df1[(df1.index>=common_start)&(df1.index<=common_end)]
df2_common=df2[(df2.index>=common_start)&(df2.index<=common_end)]
display(df1_common.info())
display(df2_common.info())

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 0 entries
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    0 non-null      float64
 1   High    0 non-null      float64
 2   Low     0 non-null      float64
 3   Close   0 non-null      float64
 4   Volume  0 non-null      int64
dtypes: float64(4), int64(1)
memory usage: 0.0 bytes

None

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 0 entries
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    0 non-null      float64
 1   High    0 non-null      float64
 2   Low     0 non-null      float64
 3   Close   0 non-null      float64
 4   Volume  0 non-null      int64
dtypes: float64(4), int64(1)
memory usage: 0.0 bytes

None

统一两份数据时间

In [ ]:
#df1=pd.read_csv("^spx_d (2).csv",index_col="Date")
#df1.index=pd.to_datetime(df1_.index,errors="coerce")
#df2=pd.read_csv("ale_d.csv",index_col="Date")
#df2.index=pd.to_datetime(df2_.index,errors="coerce")
#start_date=df1_common.index.min()
#end_date=df1_common.index.max()
#full_dates=pd.date_range(start=start_date,end=end_date)
#print(len(full_dates))

#df1_aligned=df1_.reindex(full_dates)
#df2_aligned=df2_.reindex(full_dates)
#print(f"生成的日期序列:\n{full_dates}")

In [ ]:
import matplotlib
import matplotlib.pyplot as plt
matplotlib.rc("font",family="MicroSoft YaHei",weight="normal",size=10)
plt.figure(figsize=(10,5))
y1=df1_common["Close"]
y2=df2_common["Close"]
plt.plot(df1_common.index,y1,label="spx",color="red")
plt.plot(df2_common.index,y2,label="ale",color="yellow")
plt.legend()
plt.grid(alpha=0.4)
plt.title("价格对照表")
plt.xlabel("日期")
plt.ylabel("收盘价")
plt.show()

In [ ]:
print(type(df1_.index))